BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://blog.starysky.top/links/
  theme: fluid
- link: https://blog.starysky.top/links/
  theme: common1
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: https://cdn.jsdelivr.net/gh/USTC-NKU/CDN@main/friend.json
  list:
  - - David
    - https://justdoit520.gitee.io
    - https://justdoit520.gitee.io/img/background-sunrise.jpg
  - - "\u706B\u55B5\u9171"
    - https://cat.dorcandy.cn
    - https://cat.dorcandy.cn/logo
  - - itsNekoDeng
    - https://dyfa.top
    - https://dyfa.top/medias/avatar.jpg
  - - "\u54C1\u5473\u82CF\u5DDE"
    - https://pwsz.com
    - https://cravatar.cn/avatar/8e5566d153dba1c372c54eae02401d96?s=50&r=g
  - - "\u6E05\u5C71\u7684\u5C0F\u7AD9"
    - https://qingshaner.com
    - https://qingshaner.oss-cn-hangzhou.aliyuncs.com/images/202205021359396.jpg
  - - "\u58A8\u6CFD"
    - https://blog.imzy.ink/
    - https://blog.imzy.ink/logo.jpg
  - - "\u98CE\u8BB0\u661F\u8FB0"
    - https://www.thyuu.com/
    - https://std.thyuu.com/avatar
  - - "\u8749\u6642\u96E8"
    - https://chanshiyu.com/
    - https://chanshiyu.com/static/media/background.ef472d798843fcea2486.jpg
  - - Nuts-sugar
    - https://nuts-sugar.gitee.io/
    - https://s1.ax1x.com/2022/07/09/jD41iR.jpg
  - - "\u957F\u8857\u77ED\u68A6"
    - https://wangyunzi.com/
    - https://blog.wangyunzi.com/avatar.png
  - - "\u8D30\u7339\u306E\u5C0F\u7A9D"
    - https://noionion.top/
    - https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg
  - - "Akilar\u306E\u7CD6\u679C\u5C4B"
    - https://akilar.top/
    - https://akilar.top/images/headimage.png
  - - elizen
    - https://elizen.me/
    - https://akilar.top/images/headimage.png
    - hello.xml
